//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public class DataFishContainer
{
		public static CoreFish fish1 = new CoreFish ("fish1", 1, 0.55f, 8, 0.5f, 1.2f,1);
		public static CoreFish fish2 = new CoreFish ("fish2", 2, 0.5f, 6, 0.5f, 1.2f,2);
		public static CoreFish fish3 = new CoreFish ("fish3", 4, 0.45f, 6, 0.5f, 1.2f,3);
		public static CoreFish fish4 = new CoreFish ("fish4", 6, 0.4f, 6, 0.5f, 1.2f,4);
		public static CoreFish fish5 = new CoreFish ("fish5", 9, 0.35f, 5, 0.5f, 1.2f,5);
		public static CoreFish fish6 = new CoreFish ("fish6", 12, 0.3f, 3, 0.5f, 1.2f,6);
		public static CoreFish fish7 = new CoreFish ("fish7", 16, 0.25f, 5, 0.5f, 0.8f,7);
		public static  CoreFish fish8 = new CoreFish ("fish8", 20, 0.2f, 3, 0.5f, 0.8f,8);
		public static CoreFish fish9 = new CoreFish ("fish9", 25, 0.15f, 2, 0.5f, 0.8f,9);
		public static CoreFish fish10 = new CoreFish ("fish10", 30, 0.1f, 2, 0.5f, 0.8f,10);
		public static CoreFish shark1 = new CoreFish ("shark1", 60, 0.05f, 2, 0.5f, 0.6f,11);
		public static CoreFish shark2 = new CoreFish ("shark2", 60, 0.02f, 2, 0.5f, 0.6f,12);

		public static CoreFish GetCoreFish (TYPEFISH type)
		{
				CoreFish coreFish = new CoreFish ();
				if (type == TYPEFISH.FISH1) {
						coreFish = fish1;
				} else if (type == TYPEFISH.FISH2) {
						coreFish = fish2;
				} else if (type == TYPEFISH.FISH3) {
						coreFish = fish3;
				} else if (type == TYPEFISH.FISH4) {
						coreFish = fish4;
				} else if (type == TYPEFISH.FISH5) {
						coreFish = fish5;
				} else if (type == TYPEFISH.FISH6) {
						coreFish = fish6;
				} else if (type == TYPEFISH.FISH7) {
						coreFish = fish7;
				} else if (type == TYPEFISH.FISH8) {
						coreFish = fish8;
				} else if (type == TYPEFISH.FISH9) {
						coreFish = fish9;
				} else if (type == TYPEFISH.FISH10) {
						coreFish = fish10;
				} else if (type == TYPEFISH.SHARK1) {
						coreFish = shark1;
				} else if (type == TYPEFISH.SHARK2) {
						coreFish = shark2;
				}

				return coreFish;
		}
}


